name: converter
description: A tool for image conversion, using terminal providing multi-optinal choices. Handles image from local and covert, store in local.
verion: 0.0.1

dependencies:
  prompter_qh: 0.0.2
  image: 2.1.4